#!/usr/bin/env python3
"""Draw the OpenCrossing dashboard icon: an original leaf in a die-cut
sticker style (white border, soft shadow, transparent background).

  tools/xbox/make_logo.py <out.png> [size]

Drawn from scratch with Pillow (no game art), so it can live in the repo.
xbox/assets/logo.png is generated by this; xbe_title_image.py turns it into
the XBE's $$XTIMAGE and default.tbn.
"""
import math
import sys

from PIL import Image, ImageDraw, ImageFilter

S = 1024  # work size; downscaled at the end for smooth edges


def bez(p0, p1, p2, p3, n=64):
    out = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        out.append((u**3 * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t**3 * p3[0],
                    u**3 * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t**3 * p3[1]))
    return out


def rot(pts, ang, cx, cy):
    c, s = math.cos(ang), math.sin(ang)
    return [(cx + (x - cx) * c - (y - cy) * s, cy + (x - cx) * s + (y - cy) * c) for x, y in pts]


def leaf_outline():
    # leaf pointing up: tip at top, base at bottom, a touch asymmetric
    tip, base = (512, 120), (512, 800)
    right = bez(tip, (820, 260), (840, 640), base)
    left = bez(base, (170, 660), (200, 250), tip)
    return right + left[1:], tip, base


def main():
    out = sys.argv[1]
    size = int(sys.argv[2]) if len(sys.argv) > 2 else 256
    ang = math.radians(-28)
    cx, cy = 512, 470

    outline, tip, base = leaf_outline()
    k = 0.88
    shrink = lambda pts: [(cx + (x - cx) * k, cy + 40 + (y - cy) * k) for x, y in pts]
    outline = shrink(outline)
    tip, base = shrink([tip, base])
    outline = rot(outline, ang, cx, cy)
    tip_r, base_r = rot([tip, base], ang, cx, cy)
    stem = rot(shrink([(512, 790), (500, 870), (470, 930)]), ang, cx, cy)

    # silhouette (leaf + stem) -> sticker border + shadow
    sil = Image.new("L", (S, S), 0)
    ds = ImageDraw.Draw(sil)
    ds.polygon(outline, fill=255)
    ds.line(stem, fill=255, width=46, joint="curve")
    border = sil.filter(ImageFilter.MaxFilter(57))
    shadow = border.filter(ImageFilter.GaussianBlur(18))

    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    sh = Image.new("RGBA", (S, S), (20, 40, 20, 0))
    sh.putalpha(shadow.point(lambda v: v * 110 // 255))
    img.alpha_composite(sh, (10, 16))
    white = Image.new("RGBA", (S, S), (255, 255, 250, 255))
    img.paste(white, (0, 0), border)

    # leaf body: vertical gradient, light upper-left to deep green
    grad = Image.new("RGBA", (S, S))
    gd = ImageDraw.Draw(grad)
    top, bot = (126, 206, 84), (46, 138, 52)
    for y in range(S):
        t = min(1.0, max(0.0, (y - 150) / 700))
        gd.line([(0, y), (S, y)], fill=tuple(int(a + (b - a) * t) for a, b in zip(top, bot)) + (255,))
    body = Image.new("L", (S, S), 0)
    ImageDraw.Draw(body).polygon(outline, fill=255)
    img.paste(grad, (0, 0), body)

    d = ImageDraw.Draw(img)
    # stem
    d.line(stem, fill=(122, 84, 44, 255), width=30, joint="curve")
    # midrib + side veins (clipped to the leaf)
    veins = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    vd = ImageDraw.Draw(veins)
    rib = (190, 236, 140, 255)
    vd.line([base_r, tip_r], fill=rib, width=18)
    ux, uy = tip_r[0] - base_r[0], tip_r[1] - base_r[1]
    ul = math.hypot(ux, uy)
    ux, uy = ux / ul, uy / ul
    nx, ny = -uy, ux
    for k in range(1, 6):
        t = k / 6.3
        px = base_r[0] + (tip_r[0] - base_r[0]) * t
        py = base_r[1] + (tip_r[1] - base_r[1]) * t
        ln = 230 * (1 - abs(t - 0.4) * 1.2)
        for side in (-1, 1):
            vx, vy = ux * 0.6 + side * nx * 0.8, uy * 0.6 + side * ny * 0.8
            vd.line([(px, py), (px + vx * ln, py + vy * ln)], fill=rib, width=11)
    clip = Image.new("L", (S, S), 0)
    ImageDraw.Draw(clip).polygon(outline, fill=255)
    clip = clip.filter(ImageFilter.MinFilter(25))
    img.paste(veins, (0, 0), Image.composite(veins.split()[3], Image.new("L", (S, S), 0), clip))
    # glossy highlight on the upper-left lobe
    hl = Image.new("L", (S, S), 0)
    ImageDraw.Draw(hl).ellipse((300, 250, 470, 420), fill=70)
    hl = Image.composite(hl.filter(ImageFilter.GaussianBlur(40)), Image.new("L", (S, S), 0), body)
    img.paste(Image.new("RGBA", (S, S), (255, 255, 255, 255)), (0, 0), hl)

    img.resize((size, size), Image.LANCZOS).save(out)
    print(f"wrote {out} ({size}x{size})")


if __name__ == "__main__":
    main()
